# This section is dedicated to Numpy
## Numpy = Numerical Python

In [1]:
import numpy as np

 ## 1. Datatypes and Attributes
 Numpy's main datatype is ndarray

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3.4],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [9]:
a2


array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](array-anatomy.png)

In [14]:
np.ndim(a1),np.ndim(a2),np.ndim(a3)

(1, 2, 3)

In [18]:
a1.shape,a2.shape,a3.shape

((3,), (2, 3), (2, 3, 3))

In [19]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [20]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [21]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
# create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.4
1,4.0,5.0,6.5


## 2. Creating Numpy Arrays

In [24]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 4, 8, 6, 2],
       [2, 8, 1, 1, 2],
       [2, 7, 3, 0, 2]], dtype=int32)

In [33]:
random_array.size

15

In [34]:
random_array.shape

(3, 5)

In [36]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.68946347, 0.9285377 , 0.33705619],
       [0.17353273, 0.32071963, 0.13463757],
       [0.57558775, 0.11368885, 0.5230553 ],
       [0.60121008, 0.69115018, 0.75774689],
       [0.91724204, 0.59244317, 0.3140092 ]])

In [37]:
random_array_2.shape

(5, 3)

In [38]:
random_array_2.size

15

In [39]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.88473557, 0.5764879 , 0.38222622],
       [0.85019158, 0.50675232, 0.99967685],
       [0.25421626, 0.93182124, 0.70170245],
       [0.56640119, 0.44434513, 0.39734471],
       [0.10939124, 0.75573278, 0.85442101]])

In [50]:
# Random number are not actually random they are set by using random seed
# Random numbers are actually sudo random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4 

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [48]:
random_array_4.shape

(5, 3)

In [49]:
random_array_4.size

15

 ## 3. Viewing Arrays and Matrices

In [53]:
# viewing unique elements in np arrya
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [54]:
a1

array([1, 2, 3])

In [55]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [56]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [57]:
a1[0]

np.int64(1)

In [58]:
a2[0]

array([1. , 2. , 3.4])

In [62]:
a2.shape

(2, 3)

In [59]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a3.shape

(2, 3, 3)

In [63]:
a2[1]

array([4. , 5. , 6.5])

In [64]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [69]:
a3.shape

(2, 3, 3)

In [70]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]], dtype=int32)

In [71]:
a4.shape

(2, 3, 4, 5)

In [72]:
a4.ndim

4

In [79]:
# select first element of second first line
a4[1][0][0][:3]

array([4, 6, 4], dtype=int32)

In [83]:
a4[1][2][3][:4]

array([0, 6, 3, 3], dtype=int32)

In [84]:
a4[:,:,:,:3]

array([[[[6, 7, 7],
         [5, 9, 8],
         [3, 0, 3],
         [2, 3, 8]],

        [[3, 3, 7],
         [9, 9, 0],
         [3, 2, 7],
         [0, 4, 5]],

        [[8, 4, 1],
         [8, 1, 1],
         [9, 3, 6],
         [0, 3, 5]]],


       [[[4, 6, 4],
         [4, 4, 8],
         [7, 5, 5],
         [5, 9, 3]],

        [[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0],
         [2, 9, 2]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0],
         [0, 6, 3]]]], dtype=int32)